# Generated by Django 5.1.4 on 2024-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_type", models.CharField(max_length=30)),
                ("time_range", models.CharField(max_length=30)),
                ("subject_name", models.CharField(max_length=300)),
                ("subject_type", models.CharField(max_length=30)),
                ("teacher", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Entries",
            },
        ),
    ]
