# Generated by Django 5.1.4 on 2024-12-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entry",
            new_name="Timetable",
        ),
        migrations.AlterModelOptions(
            name="timetable",
            options={},
        ),
    ]
